spring.application.name=OAuthDemo

spring.security.oauth2.client.registration.google.client-id=45990006869-99bk9s1o2p97cdn6dtno3ge0ta7vems3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.github.client-id=Ov23ctwQeHuYalSShHBZ
spring.security.oauth2.client.registration.github.client-secret=0a90d366201668d59684ead474b121e4eba6cc61